### PR TITLE
Remove debug log

### PR DESCRIPTION
**Pull request by MoritzKn**

### CODE REVIEW

**Comment by dirk-thomas** [comment]
There are a few other debug message in this package. In case users run into problems it can be quite helpful to have those in the console. Is there a specific reason why you propose to remove this specific debug message?

**Comment by MoritzKn** [comment]
This debug log has no context and therefore is a bit irritating. Also this statement always logs -- not just on error.

**Comment by dirk-thomas** [comment]
In the case of an error it already logs a message in this line: https://github.com/atom-community/sync-settings/blob/ca1c7feaee35a1c670e1b9ef91e0a575db993928/lib/sync-settings.coffee#L86

In the case of no error it logs a message in this line: https://github.com/atom-community/sync-settings/blob/ca1c7feaee35a1c670e1b9ef91e0a575db993928/lib/sync-settings.coffee#L95

The only case currently not cover would be a result without an error but which doesn't have the expected information (`res.history[0].version`). I created #312 with a modified version of this patch. Does that look reasonable to you?

**Comment by MoritzKn** [comment]
@dirk-thomas Looks perfect!

**Comment by dirk-thomas** [comment]
Thank you the initial contribution and checking the other PR. I will close this then and merge the referenced PR.

**Pull request closed without merging**
