### PR TITLE
Sync install with notifications

### PR DESCRIPTION
**Pull request by slavaGanzin**
I have near 100 packages on one machine. They halt my other PC while installing asynchroneously.

### CODE REVIEW

**Comment by dirk-thomas** [comment]
I tried this patch with my Gist which needs to restore ~60 packages. With the patch the progress shows nice per package progress notifications but takes 4.5 minutes. Without there is no feedback to the user but after 45 s everything is installed.

It would be nice if the user could get the benefit of both - get notifications about the progress while still running the installations in parallel.

**Comment by dirk-thomas** [comment]
I have created #311 which adds similar notifications but keeps running the installation asynchronously (which keeps running in a shorter time but with higher system load).

**Comment by slavaGanzin** [comment]
@dirk-thomas I have no problems on SSD, but did you try on HDD (that's why I write everything syncroneously)

**Comment by dirk-thomas** [comment]
I actually see your point now. I guess something "in between" would be nice: do some work in parallel to not overload the system but not to the extreme of sequential execution which takes significantly longer. I will try to update #311 somehow...

**Pull request closed without merging**
