### PR TITLE
Merge pull request #464 from UziTech/octokit

### LINKED ISSUE #463: Received a... few "...using the `access_token` query parameter is deprecated." emails today
I had received a few emails from Github today, all saying the same thing, pointing to my syncing `gist` file...

> Hi @jpartain89, 
> 
> On February 4th, 2020 at 03:26 (UTC) your personal access token (Atom Syncing) using NodeJS HTTP Client was used as part of a query parameter to access an endpoint through the GitHub API: 
> 
> api.github.com/gists/###hidden_because_i_said_so###
> 
> Please use the Authorization HTTP header instead, as using the `access_token` query parameter is deprecated. 
> 
> Depending on your API usage, we'll be sending you this email reminder once every 3 days for each token and User-Agent used in API calls made on your behalf. 
> Just one URL that was accessed with a token and User-Agent combination will be listed in the email reminder, not all. 
> 
> Visit developer.github.com/changes/2019-11-05-deprecated-passwords-and-authorizations-api/#authenticating-using-query-parameters for more information. 
> 
> Thanks, 
> The GitHub Team 

Any plan/word on updating this?

Thanks.

### PR DESCRIPTION
**Pull request by UziTech**
Decaffeinate and update dependencies

fixes #463

I added `eslint-config-standard` for the eslint config. The code isn't very pretty from being decaffeinated but it works.

All dependencies are updated.

I updated the `package-manager` script as well from `settings-view`

Removed dependencies `emissary` and `q` 

Tests all pass locally. It looks like travis doesn't have a valid PAT so api calls are rate limited.

### CODE REVIEW

**Comment by UziTech** [comment]
I am planning on updating the other dependencies while I'm at it, I figured I would open this PR for discussion if there is anything specific I should use. (like eslint config)

**Comment by UziTech** [comment]
@atom-community if you need a new maintainer for this repo (and/or other repos) I would love to help out.

**Comment by Cam** [comment]
@UziTech If there is no movement here you should release your fork as a new package 👍

**Comment by UziTech** [comment]
@dirk-thomas are you still maintaining this repo?

**Comment by dirk-thomas** [comment]
> are you still maintaining this repo?

No, I have moved away from Atom quite some time ago.

**Comment by dirk-thomas** [comment]
> If there is no movement here you should release your fork as a new package

I suggest to rather poke the current owner of the repo to consider giving permissions to a new maintainer rather than forking.

**Comment by UziTech** [comment]
@dirk-thomas do you know who the current owner is?

**Comment by dirk-thomas** [comment]
> do you know who the current owner is?

Beside me @groupsky and @jerone are listed in the team associated to this repo.

**Comment by UziTech** [comment]
@groupsky @jerone are either of you able to help with this?

**Comment by jerone** [comment]
@UziTech I have moved away from Atom for a long time. Ping me again over a few days if @groupsky doesn't respond. I can't add you to the @atom-community/sync-settings-maintainers [team](https://github.com/orgs/atom-community/teams/sync-settings-maintainers) (one of the @atom-community/owners has to do that, I think), but I can add you to this repo.

**Comment by smashwilson** [comment]
@UziTech I just sent you an invite to join @atom-community/sync-settings-maintainers. Thanks for offering to help, and let me know if you need anything else! ❤️

**Comment by UziTech** [comment]
@smashwilson Thanks. Is there any guidelines on maintaining this repo (e.g. use certain eslint config, etc.) and am I able to publish releases to atom.io?

**Comment by UziTech** [comment]
I use `semantic-release` for all of my packages. It has been a while since I used ol' `apm publish`. I figured it out but accidentally released it as `v2.0.0` lol.

**Comment by smashwilson** [comment]
> Is there any guidelines on maintaining this repo (e.g. use certain eslint config, etc.) 

I don't know of any. But @simurai also literally just added me to this org last night, so I wouldn't consider myself an authority :sweat_smile:

> am I able to publish releases to atom.io?

Looks like it, so hooray!

**Comment by Arcanemagus** [comment]
> am I able to publish releases to atom.io?

As far as I know anyone with write access to a repository can publish versions to atom.io.

**Pull request merged**
