### PR TITLE
Added proxy option.

### PR DESCRIPTION
**Pull request by LastLeaf**

### CODE REVIEW

**Comment by LastLeaf** [comment]
Sorry. Just sent a wrong pr. Please ignore.

**Comment by LastLeaf** [comment]
I added a `proxy` option to allow proxy set manually in my branch. Merge if you think it is useful :)

**Comment by dirk-thomas** [comment]
Please see other tickets (e.g. #142) which mention how to use the existing proxy settings. I don't think anything in this package needs to be changed for that.

**Comment by eltian** [comment]
At least in my case, I couldn't make sync-settings use the existing proxy settings (env vars, apm's proxy, etc). This is a nice solution, beats editing the source code every time I change the password in my proxy.

**Comment by dirk-thomas** [comment]
@eltian while this patch might make it work for you I don't think that it will be merged. There is already a way to configure a proxy. Therefore it would be better to debug why it didn't work for you. Since it does work for others out might just be a configuration problem...

**Comment by nerfviking1** [comment]
Sorry for commenting on a closed issue, but this is the first one that comes up for me in google, so other people might wander in here too.  See this comment for a work-around for situations where you proxy doesn't seem to work even if it's configured:

https://github.com/atom-community/sync-settings/issues/273#issuecomment-233842283

**Pull request closed without merging**
