### PR TITLE
feat: add proxy setting

### LINKED ISSUE #619: Can't set proxy settings
I have a problem with using this package when behind a proxy. I looked for all already created issues in this repo and couldn't find a way to set it up properly.

I'm using Manjaro Linux and have proxy env var (http_proxy, https_proxy, HTTP_PROXY, HTTPS_PROXY, etc.) set up. Atom gets its proxy settings from the env var. Sync settings does not even tho all issues here say it should be.

I found [this comment in #273](https://github.com/atom-community/sync-settings/issues/273#issuecomment-233842283) that shows the solution with sync-settings.coffee but I have no idea how to use that. I'd be very grateful if someone could help me.

### PR DESCRIPTION
**Pull request by UziTech**
Add a proxy setting for gist location.

defaults to `HTTPS_PROXY`, `https_proxy`, `HTTP_PROXY`, or `http_proxy` environment variable.

fixes #619

### CODE REVIEW

**Comment by baatochan** [comment]
I would be very happy to test that but I don't know how to build and install this package with this commit. I've only ever installed atom packages via atom settings.

**Comment by UziTech** [comment]
You will have to do the following:

- Uninstall current sync-settings package in Atom
- Clone the repo: `git clone https://github.com/uzitech/sync-settings`
- Move to the source directory: `cd sync-settings`
- Checkout the branch: `git checkout origin/proxy`
- Run `apm link`
- Restart Atom

**Comment by baatochan** [comment]
Before you responded I'd found another instruction [here](https://discuss.atom.io/t/manually-install-package/9251/12) and was able to install this version of package. 

I can confirm that now it works, but there is one edge case when it doesn't. If I have set env var for proxy and I switch to network without proxy there is no way I can switch sync settings to not use the proxy. Entering `""`, `''`, ' ' into setting field (and I believe anything there) shows error: You must specify a "protocol" for the proxy type (http, https, socks, socks4, socks4a, socks5, socks5h, pac+data, pac+file, pac+ftp, pac+http, pac+https)

**Comment by UziTech** [comment]
I added a checkbox in the settings to disable the proxy even when it is set. Does that work for you?

**Comment by baatochan** [comment]
It works nice :+1:

**Comment by UziTech** [comment]
Thanks for helping with this. I'll add some regression tests and get this released soon.

**Comment by Novocastrian** [comment]
Hi there, 

I've entered my employer's proxy details into the settings as below (proxy.my.employer:8080):
image
However, when I restart Atom, it complains about the proxy type. 
image
How do I fix this?

**Comment by UziTech** [comment]
@Novocastrian it looks like you need to add the protocol to the URL (`http` or `https`)

**Comment by UziTech** [comment]
You can see the supported protocols [here](https://www.npmjs.com/package/proxy-agent)

**Comment by Novocastrian** [comment]
> 
> 
> @Novocastrian it looks like you need to add the protocol to the URL (`http` or `https`)

Yep! You're correct. I assumed that if you didn't declare HTTPS it would use HTTP. adding "HTTP://" to the start of the proxy address and rebooting fixed the issue for me.

**Pull request merged**
